before:
  hooks:
    - go mod tidy
builds:
  - id: deploy-cli
    main: ./cli
    binary: deploy-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
  - id: deploy-agent
    main: ./agent
    binary: deploy-agent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
    - goos: windows
      format: zip
    files:
      - LICENSE
      - README.md
snapshot:
  name_template: "{{ .Version }}"
changelog:
  use: github
  sort: asc
  abbrev: 0
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?bug(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'typo'
    include:
      - "^feat:"
      - "^bug:"